import asyncio

import pytest

import orchestrator


VALID_APP = """
from flask import Flask
app = Flask(__name__)

@app.route('/')
def index():
    return 'ok'

if __name__ == '__main__':
    app.run(port=3456)
"""


@pytest.mark.parametrize(
    "content",
    [
        "requests",
        "https://example.com/pkg.whl",
        "git+https://example.com/repo.git",
        "-e ../localpkg",
        "--extra-index-url https://example.com/simple",
        "../localpkg",
    ],
)
def test_requirements_reject_everything_except_flask(content):
    with pytest.raises(ValueError, match="Seule la ligne 'flask'"):
        orchestrator.validate_requirements_content(content)


def test_requirements_accepts_only_flask_with_blank_lines_and_comments():
    orchestrator.validate_requirements_content("\n# generated by app creator\nflask\n")


def test_invalid_requirements_are_refused_before_pip(monkeypatch, tmp_path):
    updates = []
    subprocess_calls = []

    async def fake_generate_app_code(description, port, last_error=""):
        return {
            "name": "bad-req",
            "files": [
                {"filename": "app.py", "content": VALID_APP},
                {"filename": "requirements.txt", "content": "requests"},
            ],
        }

    async def fake_db_update(app_id, **kwargs):
        updates.append(kwargs)

    async def fake_create_subprocess_exec(*args, **kwargs):  # pragma: no cover - must not run
        subprocess_calls.append((args, kwargs))
        raise AssertionError("pip ne doit pas etre appele avec un requirements invalide")

    monkeypatch.setattr(orchestrator, "generate_app_code", fake_generate_app_code)
    monkeypatch.setattr(orchestrator, "db_update", fake_db_update)
    monkeypatch.setattr(orchestrator.asyncio, "create_subprocess_exec", fake_create_subprocess_exec)

    async def collect():
        events = []
        async for event in orchestrator.creation_pipeline(1, "demo", str(tmp_path / "project"), 3456):
            events.append(event)
        return events

    events = asyncio.run(collect())

    assert subprocess_calls == []
    assert any(update.get("status") == "failed" for update in updates)
    assert any("requirements.txt refuse" in event for event in events)
